const fs = require("node:fs");
const names = [
  "ProductRegistry",
  "VerificationRegistry",
  "SupplyChainTracker",
  "CounterfeitReporter",
];
const source = names
  .map(
    (name) =>
      `export const ${name}ABI = ${JSON.stringify(JSON.parse(fs.readFileSync(`artifacts/contracts/${name}.sol/${name}.json`)).abi, null, 2)} as const;`,
  )
  .join("\n\n");
fs.writeFileSync(
  "lib/contracts/abis.ts",
  "// Generated by scripts/export-abis.cjs from Hardhat artifacts. Do not edit.\n" +
    source +
    "\n",
);

const crypto = require("node:crypto");
const { keccak256 } = require("viem");
const identity = {};
for (const name of names) {
  const a = JSON.parse(
    fs.readFileSync(`artifacts/contracts/${name}.sol/${name}.json`),
  );
  identity[name] = {
    sourceHash: crypto
      .createHash("sha256")
      .update(fs.readFileSync(`contracts/${name}.sol`))
      .digest("hex"),
    abiHash: crypto
      .createHash("sha256")
      .update(JSON.stringify(a.abi))
      .digest("hex"),
    codeHash: keccak256(a.deployedBytecode),
  };
}
fs.writeFileSync(
  "lib/contracts/source-identity.json",
  JSON.stringify(identity, null, 2) + "\n",
);
